logging:
  level:
    org:
      springframework: INFO
    de:
      samply:
        samplexchange: DEBUG
app:
  version: '@project.version@'
  source:
    url: "${SOURCE_URL}"
    auth-type: "${SOURCE_AUTH_TYPE}"
    username: "${SOURCE_USERNAME:}"
    password: "${SOURCE_PASSWORD:}"
    bearer-token: "${SOURCE_BEARERTOKEN:}"
    disable-ssl: "${SOURCE_DISABLE_SSL:false}"
    keycloak:
      token-url: "${SOURCE_KEYCLOAK_TOKEN_URL:}"
      client-id: "${SOURCE_KEYCLOAK_CLIENT_ID:}"
      client-secret: "${SOURCE_KEYCLOAK_CLIENT_SECRET:}"
  target:
    url: "${TARGET_URL}"
    auth-type: "${TARGET_AUTH_TYPE}"
    username: "${TARGET_USERNAME:}"
    password: "${TARGET_PASSWORD:}"
    bearer-token: "${TARGET_BEARERTOKEN:}"
    disable-ssl: "${TARGET_DISABLE_SSL:false}"
    keycloak:
      token-url: "${TARGET_KEYCLOAK_TOKEN_URL:}"
      client-id: "${TARGET_KEYCLOAK_CLIENT_ID:}"
      client-secret: "${TARGET_KEYCLOAK_CLIENT_SECRET:}"
profile: "${PROFILE:none}"
fileexportpath: "${FILE_EXPORT_PATH:}"
kind: Application